### ISSUE TITLE
ZodError

### ISSUE THREAD

**Issue by dtrikannad** [Neuvernetzung/ts-ics#133] opened 2024-12-14 22:02 UTC
I'm currently running ts-ics@1.5.0 and it works great. I'm trying to update it to use ts-ics@1.6.3, but get the following error when trying to execute parseIcsCalendar(icsCalendarString).

```
ZodError: [
      {
        "received": "OPAQUE\n\n",
        "code": "invalid_enum_value",
        "options": [
          "TRANSPARENT",
          "OPAQUE"
        ],
        "path": [
          "events",
          0,
          "timeTransparent"
        ],
        "message": "Invalid enum value. Expected 'TRANSPARENT' | 'OPAQUE', received 'OPAQUE\n\n'"
      },
      {
        "validation": "email",
        "code": "invalid_string",
        "message": "Invalid email",
        "path": [
          "events",
          0,
          "attendees",
          0,
          "email"
        ]
      }
]
    
```

here is my icsCalendarString (but i've redacted some text to save the innocent):

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20241030T060000
DTEND;TZID=America/Los_Angeles:20241030T070000
DTSTAMP:20241029T135708Z
ORGANIZER;CN=Deep Trikannad:mailto:some_email_here@example.com
UID:some_google_calendar_uid_here@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE
 ;CN=some_email_here@example.net;X-NUM-GUESTS=0:mailto:some_email_here@examp
 le.net
X-GOOGLE-CONFERENCE:https://meet.google.com/some-conference-id-here
X-MICROSOFT-CDO-OWNERAPPTID:695581578
CREATED:20241029T135706Z
DESCRIPTION:<p><br>ââââââââââ<br><br>Deep Trikannad is inviting you to a sc
 heduled Zoom meeting.<br><br>Join Zoom Meeting<br>https://us06web.zoom.us/j
 /84879004110?pwd=some_zoom_password_here<br><br>Meeting ID: 848 79
 00 4110<br>Passcode: 801833<br><br>---<br><br>One tap mobile<br>+1669444917
 1\\,\\,84879004110#\\,\\,\\,\\,*801833# US<br>+12532050468\\,\\,84879004110#\\,\\,\\,\\
 ,*801833# US<br><br>---<br><br>Dial by your location<br>â¢ +1 669 444 9171 U
 S<br>â¢ +1 253 205 0468 US<br>â¢ +1 253 215 8782 US (Tacoma)<br>â¢ +1 346 248 
 7799 US (Houston)<br>â¢ +1 719 359 4580 US<br>â¢ +1 720 707 2699 US (Denver)<
 br>â¢ +1 305 224 1968 US<br>â¢ +1 309 205 3325 US<br>â¢ +1 312 626 6799 US (Ch
 icago)<br>â¢ +1 360 209 5623 US<br>â¢ +1 386 347 5053 US<br>â¢ +1 507 473 4847
  US<br>â¢ +1 564 217 2000 US<br>â¢ +1 646 558 8656 US (New York)<br>â¢ +1 646 
 931 3860 US<br>â¢ +1 689 278 1000 US<br>â¢ +1 301 715 8592 US (Washington DC)
 <br><br>Meeting ID: 848 7900 4110<br>Passcode: passcode_here<br><br>Find your loca
 l number: https://us06web.zoom.us/u/not_available<br><br><br><br>ââââââââââ</p
 >\\n\\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:
 ~:~:~:~:~::~:~::-\\nJoin with Google Meet: https://meet.google.com/some-jsg-
 dnw\\nOr dial: (US) +1 337-346-2722 PIN: NOTAVAILABLE#\\nMore phone numbers: htt
 ps://tel.meet/fec-ujsg-dnw?pin=NA-6796382590&hs=7\\n\\nLearn more about Meet 
 at: https://support.google.com/a/users/answer/9282720\\n\\nPlease do not edit
  this section.\\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~:~:~::~:~::-
LAST-MODIFIED:20241029T135706Z
LOCATION:https://us06web.zoom.us/j/84879004110?pwd=41Itl7Kbf5ZcxWYg8z15Xxtn
 xxxxx8.1
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:abcd Google to MS
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H10M0S
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P1D
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by timheerwagen** [comment] 2024-12-14 22:50
Thank you for your bug report, I was able to reproduce the bug on 1.6.3, but please try version 1.6.5, it should be fixed there.

**Closed** 2024-12-16 08:38 UTC

**Comment by dbondarchuk** [comment] 2025-04-11 18:54
Hi @timheerwagen 
i tried v 1.6.5 an 1.6.8 and I get this error when trying to parse iCloud CALDAV event: 
```
ZodError: [\n  {\n    "received": "OPAQUE\\n",\n    "code": "invalid_enum_value",\n    "options": [\n      "TRANSPARENT",\n      "OPAQUE"\n    ],\n    "path": [\n      "timeTransparent"\n    ],\n    "message": "Invalid enum value. Expected 'TRANSPARENT' | 'OPAQUE', received 'OPAQUE\\n'"\n  }\n]\n    at get error [as error] (/Users/dmytrobondarchuk/my-projects/vivid/apps/web/.next/server/chunks/node_modules_zod_lib_index_mjs_78df62a6._.js:5209:31)\n    at ZodIntersection.parse (/Users/dmytrobondarchuk/my-project…sers/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:234:21)\n    at async handleRequest (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:422:24)\n    at async requestHandlerImpl (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:446:13)\n    at async Server.requestListener (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/start-server.js:158:13)
```

**Comment by timheerwagen** [comment] 2025-04-12 18:20
> Hi [@timheerwagen](https://github.com/timheerwagen) i tried v 1.6.5 an 1.6.8 and I get this error when trying to parse iCloud CALDAV event:
> 
> ```
> ZodError: [\n  {\n    "received": "OPAQUE\\n",\n    "code": "invalid_enum_value",\n    "options": [\n      "TRANSPARENT",\n      "OPAQUE"\n    ],\n    "path": [\n      "timeTransparent"\n    ],\n    "message": "Invalid enum value. Expected 'TRANSPARENT' | 'OPAQUE', received 'OPAQUE\\n'"\n  }\n]\n    at get error [as error] (/Users/dmytrobondarchuk/my-projects/vivid/apps/web/.next/server/chunks/node_modules_zod_lib_index_mjs_78df62a6._.js:5209:31)\n    at ZodIntersection.parse (/Users/dmytrobondarchuk/my-project…sers/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:234:21)\n    at async handleRequest (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:422:24)\n    at async requestHandlerImpl (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/router-server.js:446:13)\n    at async Server.requestListener (/Users/dmytrobondarchuk/my-projects/vivid/node_modules/next/dist/server/lib/start-server.js:158:13)
> ```

Hi, could you please provide the ics string you try to parse? Looks like an error in the parser, because there is a line break left behind the enum value. "OPAQUE\\n"

**Comment by dbondarchuk** [comment] 2025-04-13 15:35
@timheerwagen 
```
"BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nDTSTAMP:20250411T173737Z\r\nSUMMARY:Test Icloud caldav\r\nTZID:America/New_York\r\nSEQUENCE:0\r\nUID:b542d9e2-8875-40bb-a679-0577e65726cd\r\nCREATED:20250411T173737Z\r\nDTSTART;TZID=America/New_York:20250411T181500\r\nDTEND;TZID=America/New_York:20250411T185000\r\nTRANSP:OPAQUE\r\nEND:VEVENT\r\nEND:VCALENDAR"
```

**Comment by dbondarchuk** [comment] 2025-04-13 15:37
@timheerwagen i think maybe because it's Apple ICloud and it uses `\r\n` ?

**Comment by timheerwagen** [comment] 2025-04-13 18:16
> [@timheerwagen](https://github.com/timheerwagen)
> 
> ```
> "BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nDTSTAMP:20250411T173737Z\r\nSUMMARY:Test Icloud caldav\r\nTZID:America/New_York\r\nSEQUENCE:0\r\nUID:b542d9e2-8875-40bb-a679-0577e65726cd\r\nCREATED:20250411T173737Z\r\nDTSTART;TZID=America/New_York:20250411T181500\r\nDTEND;TZID=America/New_York:20250411T185000\r\nTRANSP:OPAQUE\r\nEND:VEVENT\r\nEND:VCALENDAR"
> ```

What is missing here is "...VERSION:2.0\r\nPRODID:ID..." because this is a required prop of the calendar component. But I can't reproduce the error with the calendarString either in 1.6.8 or in the latest 2.0.3.

**Comment by dbondarchuk** [comment] 2025-04-14 15:02
So it seems to be related to this: 

When I use data from Nextcloud caldav, while the event is parsed successfully, summary has extra `\n` at the end:

Data:
```
BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Sabre//Sabre VObject 4.5.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VEVENT\r\nCREATED:20250414T145851Z\r\nDTSTAMP:20250414T145859Z\r\nLAST-MODIFIED:20250414T145859Z\r\nSEQUENCE:2\r\nUID:dc01b8b9-bf91-4246-ad1c-69eb6505ac0f\r\nDTSTART:20250417T080000Z\r\nDTEND:20250417T223000Z\r\nSTATUS:CONFIRMED\r\nSUMMARY:Busy nextcloud\r\nEND:VEVENT\r\nEND:VCALENDAR
```

Parsed: 

<img width="353" alt="Image" src="https://github.com/user-attachments/assets/dd7fb888-f2ce-42f3-858a-5bbdab4db68f" />

**Comment by dbondarchuk** [comment] 2025-04-14 15:07
And looking into convert operation:
```'BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20250414T143349Z
SUMMARY:Test ICloud calendar
TZID:America/New_York
SEQUENCE:0
UID:7de6214a-81fe-49d3-9dfc-28ef59d68eaa
CREATED:20250414T143349Z
DTSTART;TZID=America/New_York:20250415T101500
DTEND;TZID=America/New_York:20250415T130500
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR'```

becomes this
```
BEGIN:VCALENDAR

DTSTAMP:20250414T143349Z
SUMMARY:Test ICloud calendar
TZID:America/New_York
SEQUENCE:0
UID:7de6214a-81fe-49d3-9dfc-28ef59d68eaa
CREATED:20250414T143349Z
DTSTART;TZID=America/New_York:20250415T101500
DTEND;TZID=America/New_York:20250415T130500
TRANSP:OPAQUE

END:VCALENDAR
```

**Comment by dbondarchuk** [comment] 2025-04-14 15:11
@timheerwagen confirmed this by removing that replace in the lib and it worked perfectly!
do you have any insight why that replace is needed?

**Comment by timheerwagen** [comment] 2025-04-14 15:15
The data you provided does not contain the extra `\n`, but even if i put it there behind the summary i can't reproduce it. 

`SUMMARY:Busy nextcloud\n\r\n` and `SUMMARY:Busy nextcloud\r\n` procudes valid output.

> And looking into convert operation:
> 
> ```
> BEGIN:VCALENDAR
> BEGIN:VEVENT
> DTSTAMP:20250414T143349Z
> SUMMARY:Test ICloud calendar
> TZID:America/New_York
> SEQUENCE:0
> UID:7de6214a-81fe-49d3-9dfc-28ef59d68eaa
> CREATED:20250414T143349Z
> DTSTART;TZID=America/New_York:20250415T101500
> DTEND;TZID=America/New_York:20250415T130500
> TRANSP:OPAQUE
> END:VEVENT
> END:VCALENDAR
> ```
> 
> becomes this
> 
> ```
> BEGIN:VCALENDAR
> 
> DTSTAMP:20250414T143349Z
> SUMMARY:Test ICloud calendar
> TZID:America/New_York
> SEQUENCE:0
> UID:7de6214a-81fe-49d3-9dfc-28ef59d68eaa
> CREATED:20250414T143349Z
> DTSTART;TZID=America/New_York:20250415T101500
> DTEND;TZID=America/New_York:20250415T130500
> TRANSP:OPAQUE
> 
> END:VCALENDAR
> ```

Looks like you are using `convertIcsEvent` instead of `convertIcsCalendar`. 

> [@timheerwagen](https://github.com/timheerwagen) confirmed this by removing that replace in the lib and it worked perfectly! do you have any insight why that replace is needed?

This removes `BEGIN:VEVENT` and `END:VEVENT` from the `Event` string.

Can you please provide a reproduction of the codes and box so I can investigate further? I can't really help you if I can only assume things.

**Comment by dbondarchuk** [comment] 2025-04-14 15:34
🤦 I think i got it.
The problem I have is coming from the fact, that the events here are coming from CalDav, and the CalDav adds `BEGIN:VCALENDAR` for each object. So while it's technically event, the lib is confused as it is not expecting the `BEGIN:VCALENDAR` header.

I switch to `convertIcsCalendar` and grab events from that, but now I don't have option to pass the timezone from CalDav calendar prop :/

**Comment by dbondarchuk** [comment] 2025-04-14 15:45
So my current solution is:
```
const calendars = await client.fetchCalendars();
      const calendar = calendars.find((c) => {
        if (!c.displayName) return false;
        if (typeof c.displayName === "string")
          return c.displayName === calendarName;

        return Object.keys(c.displayName)[0] === calendarName;
      });

      if (!calendar) {
        throw new Error(`Can't find calendar '${calendarName}'`);
      }

      const timezones =
        (calendar.timezone
          ? parseIcsCalendar(calendar.timezone).timezones
          : undefined) || [];

const objects = await client.fetchCalendarObjects({
        calendar: calendar,
        expand: true,
        urlFilter: () => true,
        timeRange: {
          start: startTime,
          end: endTime,
        },
      });

      const events = objects
        .map((obj) => {
          const dataStr = obj.data as string;
          const eventStr = dataStr.match(getEventRegex)?.[0];
          if (!eventStr) return null;

          return parseIcsEvent(eventStr, { timezones });
        })
        .filter((e) => !!e);
```

which seems to work fine.
I will leave this here as example for anyone who may encounter same error.

Thanks, @timheerwagen !
